Add our path resolution policy to developing
fox-it/dissect-docs pull request #45
Opened 2024-02-01 14:09 UTC by Miauwkeru

(DIS-2622)

2024-02-02 00:01 UTC, Schamper requested changes

2024-02-02 00:01 UTC, Schamper commented on docs/source/contributing/developing.rst
> +While the ``--hash`` flag adds extends the ``--resolve`` information and includes the ``digest`` to it.
```suggestion
The ``--hash`` flag extends the ``--resolve`` information and includes a ``_digest`` suffixed field as well, which contains the file digest triple (if available):
```

2024-02-02 18:45 UTC, Schamper commented on docs/source/contributing/developing.rst
> +While the ``--hash`` flag adds extends the ``--resolve`` information and includes the ``digest`` to it.
The `if available` was a reference to if the file exists, but I've reworded it.

2024-02-05 12:34 UTC, pyrco requested changes

2024-02-05 12:34 UTC, pyrco commented on docs/source/contributing/developing.rst
> +Starting from Dissect version 3.11, we decided that new plugins will only provide the original parsed ``path`` value in its records.
```suggestion
Starting from Dissect version 3.11, the policy is for plugins to only provide the original parsed ``path`` value in returned records.
```

2024-02-05 12:34 UTC, pyrco commented on docs/source/contributing/developing.rst
> +This keeps the information inside the records as close to the truth as possible.
```suggestion
We recommend external contributors to follow the same policy,
this keeps the path information in the records as close to the truth as possible.
```

2024-02-05 12:34 UTC, pyrco commented on docs/source/contributing/developing.rst
> +A resolved path can still be accessed by using the ``--resolve`` or ``--hash`` flags in :doc:`target-query </tools/target-query>`.
```suggestion
Resolved paths can be accessed by using the ``--resolve`` or ``--hash`` flags in :doc:`target-query </tools/target-query>`.
```

2024-02-06 08:45 UTC, pyrco submitted a review, later dismissed

2024-02-06 12:51 UTC, Schamper approved these changes

2024-02-06 13:38 UTC, merged