Add explanation about namespace plugins
fox-it/dissect-docs pull request #61
Opened 2024-08-20 12:51 UTC by Zawadidone

This is related to https://github.com/fox-it/dissect.target/issues/822.

2024-11-03 18:08 UTC, Schamper requested changes

2024-11-03 18:08 UTC, Schamper commented on docs/source/usage/first-steps/incident-handler.rst
> +Be aware that executing a namespace plugin like ``browser.cookies`` in conjunction with the plugin ``chrome.cookies``, that
```suggestion
Be aware that when executing a namespace plugin like ``browser.cookies`` in conjunction with the plugin ``chrome.cookies``,
```

2024-11-03 19:09 UTC, Zawadidone commented on docs/source/usage/first-steps/incident-handler.rst
> +Be aware that executing a namespace plugin like ``browser.cookies`` in conjunction with the plugin ``chrome.cookies``, that
Fixed

2024-11-04 09:18 UTC, Schamper approved these changes

2024-11-04 09:18 UTC, merged